name: watch_store_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_localization: ^0.2.0
  flutter_svg: ^2.0.10+1
  carousel_slider: ^4.2.1
  persian_number_utility: ^1.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.11

flutter:
  uses-material-design: true

  assets:
    - assets/images/


  fonts:
    - family: Vazir
      fonts:
        - asset: assets/fonts/VAZIR-REGULAR.TTF
          weight: 300
        - asset: assets/fonts/VAZIR-BOLD.TTF
          weight: 700
