name: watch_store_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_localization: ^0.2.0
  flutter_svg: ^2.0.10+1
  carousel_slider: ^4.2.1
  persian_number_utility: ^1.1.4
  flutter_bloc: ^8.1.6
  dio: ^5.5.0+1
  flutter_timer_countdown: ^1.0.7
  shared_preferences: ^2.2.3
  image_cropper: ^7.1.0
  image_picker: ^1.1.2
  flutter_osm_plugin: ^1.2.0
  equatable: ^2.0.5
  flutter_widget_from_html: ^0.15.1
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.11

flutter:
  uses-material-design: true

  assets:
    - assets/images/


  fonts:
    - family: Vazir
      fonts:
        - asset: assets/fonts/Vazir-Regular-FD.ttf
          weight: 300
        - asset: assets/fonts/Vazir-Medium-FD.ttf
          weight: 500
        - asset: assets/fonts/Vazir-Bold-FD.ttf
          weight: 700
